[package]
org = "cybercare"
name = "CyberCare"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "2.0.29"