[QuickRoute.password]	
secret = "3f2e4c5b7d9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h1i2j3k4l5m6"

[QuickRoute.jwt]
secret = "ab12cd34ef56gh78ij90kl12mn34op56qr78st90uv12wx34yz56ab78cd90ef12"

[QuickRoute.db]	
host = ""
username = ""	
passsword = ""
database = ""
port = 1234


[QuickRoute.email]	
server = ""
username = ""
password = ""

[QuickRoute.OpenAI]
API_TOKEN = ""
API_URL = "https://api.openai.com/v1/chat/completions"