# CyberCare Configuration File
# Update these values according to your environment

[CyberCare.database]
host = "localhost"
port = 5432
username = "cybercare_user"
password = "your_db_password"
database = "cybercare_db"

[CyberCare.jwt]
secret = "your_jwt_secret_key_here_make_it_strong_and_unique"
issuer = "CyberCare"
expiryTime = 3600  # 1 hour in seconds

[CyberCare.apis]
hibp_api_key = "your_haveibeenpwned_api_key"
virustotal_api_key = "your_virustotal_api_key"

[CyberCare.email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
username = "your_email@gmail.com"
password = "your_app_password"
from_address = "noreply@cybercare.com"

[CyberCare.cert]
notification_email = "cert@example.gov"
export_endpoint = "https://cert.gov/api/threats"  # if available

[CyberCare.server]
port = 8080
cors_allowed_origins = ["http://localhost:3000", "http://localhost:5173"]

[CyberCare.security]
password_salt = "your_password_salt_here"
rate_limit_requests = 100
rate_limit_window = 60  # seconds