[package]
org = "sentra"
name = "backend"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"

[[dependency]]
org = "ballerina"
name = "sql"

[[dependency]]
org = "ballerinax"
name = "mysql"

[[dependency]]
org = "ballerina"
name = "jwt"

[[dependency]]
org = "ballerina"
name = "crypto"

[[dependency]]
org = "ballerina"
name = "uuid"

[[dependency]]
org = "ballerina"
name = "time"

[[dependency]]
org = "ballerina"
name = "email"

[[dependency]]
org = "ballerina"
name = "log"

[[dependency]]
org = "ballerina"
name = "encoding"

[[dependency]]
org = "ballerina"
name = "random"