# config this file according to your credentials

[QuickRoute.password]	
secret = "xN5$2mL@qP7!eW#yT^9uB%8dZ&jC6Q*4R#oKp1^V"

[QuickRoute.jwt]
secret = "q1W2@r3E#t4Y*u7I8&dZ1$9oX@6P^mN!lK#bC9wQ%rT9zL"

[QuickRoute.db]	
host = "localhost"
username = "root"	
passsword = "200528100634@Vn"
database = "QuickRoute"
port = 3306


[QuickRoute.email]	
server = "smtp.gmail.com"
username = "hiranyagunawardhane@gmail.com"
password = "hguy gxbe gxmu dlkb"

[QuickRoute.OpenAI]
API_TOKEN = "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"
API_URL = "https://api.openai.com/v1/chat/completions"